### ISSUE TITLE
Problem with CloudFlare server

### ISSUE THREAD

**Issue by treyweaver** [boostorg/beast#2236]
Version that comes with boost 1.74

I am unable to get the sample websocket_client_async_ssl.cpp to connect
to wss://zellowork.io on a cloudflare server.

https://github.com/boostorg/beast/blob/develop/example/websocket/client/
async-ssl/websocket_client_async_ssl.cpp

The error I get during on "on_ssl_handshake" is "sslv3 alert handshake
failure"

No special certificates or keys are needed because I can connect
straight-away with wscat or websoccat or even curl if I use curl: 
        curl -vv https://zellowork.io/ws/mesh

**Comment by madmongo1** [comment]
Hi there. What did you type on the command line?

**Comment by madmongo1** [comment]
I seem to remember having to update the certificates that are hard-code in the source. I think that was in boost 1.75

I'll run the latest version here and see if that helps.

**Comment by madmongo1** [comment]
OK, the problem is that the examples only include a small set of the root certificates that are in use today and your server is presenting a certificate not recognised by the example.

I fixed this by copying the contents of the file `/etc/ssl/certs/ca-bundle.crt` into the function body of `load_root_certificates()`.

Here is the commit:

https://github.com/boostorg/beast/pull/2237/commits/ee36fced197b4cb8c3b400c12877c7bf207583ef

**Comment by treyweaver** [comment]
I tried the new load_root_certificates()  and got the same result.

The root_certificates.hpp file I tried was 265114 bytes long; just to make sure I am using the correct one.

Or where you saying that I need to use my own /etc/ssl/certs/ca-bundle.crt file?  I don't have that file but I do have a ca-certificates.crt file.

Thanks for your help.

**Comment by treyweaver** [comment]
Richard,

Can you reopen this?  This fix did not fix my issue.  I used openssl to get the certificates from zelloworks.io and that did not seem to work either.

Thanks for your help!
Trey Weaver

**Comment by madmongo1** [comment]
In what way did it not work for you? When I ran the code it connected , performed the ssl handshake correctly and then waited.
It then disconnected.
This seems to be “correct” behaviour given the problem description.

are you saying that for you the SSL layer does not ha debarked still?

**Comment by treyweaver** [comment]
Richard,

The error that I am getting is:  
ssl_handshake: sslv3 alert handshake failure

Same as before.  I am on a Debian-10 machine running on ARM.  Tomorrow morning I am planning on running the same code  Debian-10 machine on Intel to see if it has the same issue.

Thanks again for your help!

**Comment by madmongo1** [comment]
Hmm. That doesn't make sense. When I applied the patch in the PR (now on develop branch) it fixes that problem for me.

**Comment by treyweaver** [comment]
The only file that you changed was the root_certificates.hpp file right?  Cause that was the only file I imported.

I am able to run these command successfully:
openssl s_client -connect zellowork.io:443 <http://zellowork.io:443/>
openssl s_client -connect zellowork.io:443 <http://zellowork.io:443/> -servername zellowork.io <http://zellowork.io/>

So I don’t think it is related to openssl.

**Comment by madmongo1** [comment]
> ssl_handshake: sslv3 alert handshake failure

This is unequivocally an SSL handshake error.

Dumb question:
Did you recompile after patching the root_certificates.hpp file?

**Comment by treyweaver** [comment]
I think I got it!

If you set up the SNI host name as *<zellowork.io:443>* rather than just *<zellowork.io>* it fails.I don't know what combination of things causes this issue:  version of openssl, verison of ASIO, Cloudflare, Arm Processor or something else but it does fail.

On open ssl on my machine this works:
*openssl s_client -connect zellowork.io:443 -servername zellowork.io*
but this fails
*openssl s_client -connect zellowork.io:443 -servername zellowork.io:443*
but these all work:
*openssl s_client -connect mozilla.com:443 <http://zellowork.io:443/> -servername mozilla.com:443*
*openssl s_client -connect google.com:443 <http://zellowork.io:443/> -servername google.com:443*
*openssl s_client -connect hover.com:443 <http://zellowork.io:443/> -servername hover.com <http://zellowork.io/>:443*
*openssl s_client -connect cloudflare.com:443 <http://zellowork.io:443/> -servername cloudflare.com:443*

Thanks for all of your help!

Here is my modified code for on_connect:

*   ** void**
*
*    on_connect(beast::error_code ec, tcp::resolver::results_type::endpoint_type ep)**
*
*    {**
*
*        std::cout << "********** on_connect..." << std::endl;**
*
*        if(ec)**
*
*            return fail(ec, "connect");**
*
*
*
*        // Update the host_ string. This will provide the value of the**
*
*        // Host HTTP header during the WebSocket handshake.**
*
*        // See **https://tools.ietf.org/html/rfc7230#section-5.4**
*
*        std::string jHost = host_;**
*
*        host_ += ':' + std::to_string(ep.port());**
*
*        std::cout << "Host: " <<  host_.c_str() << std::endl;**
*
*
*
*        // Set a timeout on the operation**
*
*        beast::get_lowest_layer(ws_).expires_after(std::chrono::seconds(30));**
*
*
*
*        // Set SNI Hostname (many hosts need this to handshake successfully)**
*
*        if(! SSL_set_tlsext_host_name(**
*
*                ws_.next_layer().native_handle(),**
*
*                jHost.c_str()))**
*
*        {**
*
*            ec = beast::error_code(static_cast<int>(::ERR_get_error()),**
*
*                net::error::get_ssl_category());**
*
*            return fail(ec, "connect");**
*
*        }**
*
*
*
*        // Perform the SSL handshake**
*
*        ws_.next_layer().async_handshake(**
*
*            ssl::stream_base::client,**
*
*            beast::bind_front_handler(**
*
*                &session::on_ssl_handshake,**
*
*                shared_from_this()));**
*
*    }**
*
**
****

**Comment by madmongo1** [comment]
The command line arguments you should be giving to the beast program are:

 `zellowork.io 443 /ws/mesh`

**Comment by treyweaver** [comment]
I actually hard coded the /ws/mesh into the code. So it is there.

Trey

**Comment by madmongo1** [comment]
OK Great, may I close this issue now?

**Comment by treyweaver** [comment]
Yes,

Again thanks for your help!

Trey
