### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by JLospinoso** [boostorg/beast#702]
In README, documentation link is broken. I suspect this is to do with Boost not yet being updated on boost.org.

### Version of Beast

n/a -- this applies to master

### Steps necessary to reproduce the problem

Visit http://www.boost.org/doc/libs/master/libs/bind/doc/html/beast/quick_start.html

### All relevant compiler information

n/a

**Comment by vinniefalco** [comment]
That's weird, I could swear I just fixed it yesterday! Would you mind refreshing the repository page and trying again?

**Comment by JLospinoso** [comment]
Still getting a 404:

404 Not Found

File "/home/www/shared/archives/live/master/libs/bind/doc/html/beast/quick_start.html" not found.

Unable to find file.

**Comment by vinniefalco** [comment]
I see it now, it looks like I missed a spot, thanks!

Please use this link for now, I will update the branch momentarily:
http://vinniefalco.github.io/beast/beast/quick_start.html

**Comment by JLospinoso** [comment]
No problem, and congrats on getting your stellar library into Boost. Great work!

**Comment by vinniefalco** [comment]
Thank you very much! If you're using Beast I would love to hear about what you're doing (just the parts you feel comfortable talking about). And if you have any problems, or what you think could be improved...any feedback you provide will help make the library better!

**Comment by vinniefalco** [comment]
This is merged
